// AUTO-GENERATED by scripts/generate-static.ts. Do not edit.
import _0 from "../../../client/dist/index.html" with { type: "file" };
import _1 from "../../../client/dist/static/css/index.7e1d5cd1.css" with { type: "file" };
import _2 from "../../../client/dist/static/js/389.f35c0a9f.js" with { type: "file" };
import _3 from "../../../client/dist/static/js/389.f35c0a9f.js.LICENSE.txt" with { type: "file" };
import _4 from "../../../client/dist/static/js/index.a1be27c8.js" with { type: "file" };
import _5 from "../../../client/dist/static/js/lib-react.50093d8d.js" with { type: "file" };
import _6 from "../../../client/dist/static/js/lib-react.50093d8d.js.LICENSE.txt" with { type: "file" };

export const embedded: Record<string, string> = {
  "/index.html": _0 as unknown as string,
  "/static/css/index.7e1d5cd1.css": _1 as unknown as string,
  "/static/js/389.f35c0a9f.js": _2 as unknown as string,
  "/static/js/389.f35c0a9f.js.LICENSE.txt": _3 as unknown as string,
  "/static/js/index.a1be27c8.js": _4 as unknown as string,
  "/static/js/lib-react.50093d8d.js": _5 as unknown as string,
  "/static/js/lib-react.50093d8d.js.LICENSE.txt": _6 as unknown as string,
};
