// AUTO-GENERATED by scripts/generate-static.ts. Do not edit.
import _0 from "../../../client/dist/index.html" with { type: "file" };
import _1 from "../../../client/dist/static/css/index.d1ce1657.css" with { type: "file" };
import _2 from "../../../client/dist/static/js/806.db2c779c.js" with { type: "file" };
import _3 from "../../../client/dist/static/js/806.db2c779c.js.LICENSE.txt" with { type: "file" };
import _4 from "../../../client/dist/static/js/index.78321be9.js" with { type: "file" };
import _5 from "../../../client/dist/static/js/lib-react.50093d8d.js" with { type: "file" };
import _6 from "../../../client/dist/static/js/lib-react.50093d8d.js.LICENSE.txt" with { type: "file" };

export const embedded: Record<string, string> = {
  "/index.html": _0 as unknown as string,
  "/static/css/index.d1ce1657.css": _1 as unknown as string,
  "/static/js/806.db2c779c.js": _2 as unknown as string,
  "/static/js/806.db2c779c.js.LICENSE.txt": _3 as unknown as string,
  "/static/js/index.78321be9.js": _4 as unknown as string,
  "/static/js/lib-react.50093d8d.js": _5 as unknown as string,
  "/static/js/lib-react.50093d8d.js.LICENSE.txt": _6 as unknown as string,
};
