// AUTO-GENERATED by scripts/generate-migrations.ts. Do not edit.
// Stub — populated by `bun run build:release` before `bun build --compile`.
export const embeddedMigrations: Record<string, string> = {};
