// AUTO-GENERATED by scripts/generate-migrations.ts. Do not edit.
import _0 from "../../drizzle/0000_lying_firedrake.sql" with { type: "file" };
import _1 from "../../drizzle/meta/0000_snapshot.json" with { type: "file" };
import _2 from "../../drizzle/meta/_journal.json" with { type: "file" };

export const embeddedMigrations: Record<string, string> = {
  "0000_lying_firedrake.sql": _0 as unknown as string,
  "meta/0000_snapshot.json": _1 as unknown as string,
  "meta/_journal.json": _2 as unknown as string,
};
