// AUTO-GENERATED by scripts/generate-migrations.ts. Do not edit.
import _0 from "../../drizzle/0000_lying_firedrake.sql" with { type: "file" };
import _1 from "../../drizzle/0001_marvelous_wendigo.sql" with { type: "file" };
import _2 from "../../drizzle/0002_serious_havok.sql" with { type: "file" };
import _3 from "../../drizzle/0003_stats_extras.sql" with { type: "file" };
import _4 from "../../drizzle/0004_cooldowns_chat.sql" with { type: "file" };
import _5 from "../../drizzle/0005_chat_block.sql" with { type: "file" };
import _6 from "../../drizzle/meta/0000_snapshot.json" with { type: "file" };
import _7 from "../../drizzle/meta/0001_snapshot.json" with { type: "file" };
import _8 from "../../drizzle/meta/0002_snapshot.json" with { type: "file" };
import _9 from "../../drizzle/meta/0003_snapshot.json" with { type: "file" };
import _10 from "../../drizzle/meta/0004_snapshot.json" with { type: "file" };
import _11 from "../../drizzle/meta/0005_snapshot.json" with { type: "file" };
import _12 from "../../drizzle/meta/_journal.json" with { type: "file" };

export const embeddedMigrations: Record<string, string> = {
  "0000_lying_firedrake.sql": _0 as unknown as string,
  "0001_marvelous_wendigo.sql": _1 as unknown as string,
  "0002_serious_havok.sql": _2 as unknown as string,
  "0003_stats_extras.sql": _3 as unknown as string,
  "0004_cooldowns_chat.sql": _4 as unknown as string,
  "0005_chat_block.sql": _5 as unknown as string,
  "meta/0000_snapshot.json": _6 as unknown as string,
  "meta/0001_snapshot.json": _7 as unknown as string,
  "meta/0002_snapshot.json": _8 as unknown as string,
  "meta/0003_snapshot.json": _9 as unknown as string,
  "meta/0004_snapshot.json": _10 as unknown as string,
  "meta/0005_snapshot.json": _11 as unknown as string,
  "meta/_journal.json": _12 as unknown as string,
};
