#!/usr/bin/env bun
import { readdir } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const CLIENT_DIST = resolve(import.meta.dir, "../../client/dist");
const OUT_FILE = resolve(import.meta.dir, "../src/static/embedded.ts");

async function* walk(dir: string): AsyncGenerator<string> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else if (entry.isFile()) yield full;
  }
}

const files: string[] = [];
if (!(await Bun.file(join(CLIENT_DIST, "index.html")).exists())) {
  console.error(`[generate-static] missing ${CLIENT_DIST}/index.html — run client build first`);
  process.exit(1);
}

for await (const abs of walk(CLIENT_DIST)) {
  files.push(relative(CLIENT_DIST, abs));
}
files.sort();

const OUT_DIR = resolve(import.meta.dir, "../src/static");
const imports = files
  .map((rel, i) => {
    const importPath = relative(OUT_DIR, join(CLIENT_DIST, rel)).replaceAll("\\", "/");
    const prefixed = importPath.startsWith(".") ? importPath : `./${importPath}`;
    return `import _${i} from "${prefixed}" with { type: "file" };`;
  })
  .join("\n");

const entries = files
  .map(
    (rel, i) => `  ${JSON.stringify(`/${rel.replaceAll("\\", "/")}`)}: _${i} as unknown as string,`,
  )
  .join("\n");

const body = `// AUTO-GENERATED by scripts/generate-static.ts. Do not edit.
${imports}

export const embedded: Record<string, string> = {
${entries}
};
`;

await Bun.write(OUT_FILE, body);
console.log(
  `[generate-static] wrote ${files.length} entries to ${relative(process.cwd(), OUT_FILE)}`,
);
