#!/usr/bin/env bun
import { readdir } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const DRIZZLE_DIR = resolve(import.meta.dir, "../drizzle");
const OUT_FILE = resolve(import.meta.dir, "../src/db/migrations-embedded.ts");
const OUT_DIR = resolve(import.meta.dir, "../src/db");

async function* walk(dir: string): AsyncGenerator<string> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else if (entry.isFile()) yield full;
  }
}

const journalPath = join(DRIZZLE_DIR, "meta/_journal.json");
if (!(await Bun.file(journalPath).exists())) {
  console.error(`[generate-migrations] missing ${journalPath}`);
  process.exit(1);
}

const files: string[] = [];
for await (const abs of walk(DRIZZLE_DIR)) {
  files.push(relative(DRIZZLE_DIR, abs));
}
files.sort();

const imports = files
  .map((rel, i) => {
    const importPath = relative(OUT_DIR, join(DRIZZLE_DIR, rel)).replaceAll("\\", "/");
    const prefixed = importPath.startsWith(".") ? importPath : `./${importPath}`;
    return `import _${i} from "${prefixed}" with { type: "file" };`;
  })
  .join("\n");

const entries = files
  .map((rel, i) => `  ${JSON.stringify(rel.replaceAll("\\", "/"))}: _${i} as unknown as string,`)
  .join("\n");

const body = `// AUTO-GENERATED by scripts/generate-migrations.ts. Do not edit.
${imports}

export const embeddedMigrations: Record<string, string> = {
${entries}
};
`;

await Bun.write(OUT_FILE, body);
console.log(
  `[generate-migrations] wrote ${files.length} entries to ${relative(process.cwd(), OUT_FILE)}`,
);
